### ISSUE TITLE
Please Reenable copy() for Tyrant Classes

### ISSUE THREAD

**Issue by JEG2** [jmettraux/rufus-tokyo#19]
Tyrant supports the hot backup feature and disabling it inside of rufus-tokyo doesn't provide any security.  The feature is still active in the server and could be reached through a simple HTTP request.  Forcing me to resort to that if I need the feature is just an inconvenience.

Sure, this feature can be dangerous.  If you need to restrict access to it though, you want to do that at the server level so it affects everyone equally.  This is the purpose of the -mask and -umask switches ttserver supports.  You could also setup access to Tokyo Tyrant through something like SSH tunneling to restrict it to specific trusted users.

Thus, I believe disabling copy() is costing a feature without a noticeable gain.

**Comment by jmettraux** [comment]
OK. Makes completely sense. I will reenable it.

**Comment by jmettraux** [comment]
todo : reenabled #copy for Tyrant (Edo and Tokyo) - closed by 3bbc937e508fee0757106db3130c53ef384679a2

(would be good to have one at hand for tyrant tables)
