### ISSUE TITLE
Should Table Classes get a query_count() to Match query_delete()?

### ISSUE THREAD

**Issue by JEG2** [jmettraux/rufus-tokyo#20]
I realize it's not a proper query option yet, which is why I hesitated to add it myself in the changes I made.  Still, it seems like a nice convenience from user code.  What do you think?

**Comment by jmettraux** [comment]
I'm for it, feel free to add it :)

**Comment by JEG2** [comment]
I added it in my fork.

**Comment by jmettraux** [comment]
Many thanks !
