### ISSUE TITLE
Unknow bug during table creating/opening.

### ISSUE THREAD

**Issue by ghost** [jmettraux/rufus-tokyo#21]
I tried to run example with the creation of a new table and here is what I got:

> require 'rubygems'
> require 'rufus/tokyo'
> t = Rufus::Tokyo::Table.new('table.tct')
> Rufus::Tokyo::TokyoError: (err 0) success
>         from /home/lumrandir/.rvm/gems/ruby/1.8.6/gems/rufus-tokyo-1.0.1/lib/rufus/tokyo/cabinet/table.rb:603:in `raise_error'
>         from /home/lumrandir/.rvm/gems/ruby/1.8.6/gems/rufus-tokyo-1.0.1/lib/rufus/tokyo/cabinet/table.rb:588:in`libcall'
>         from /home/lumrandir/.rvm/gems/ruby/1.8.6/gems/rufus-tokyo-1.0.1/lib/rufus/tokyo/cabinet/table.rb:136:in `initialize'
>         from (irb):14:in`new'
>         from (irb):14
>         from /home/lumrandir/.rvm/ruby-1.8.6-p383/lib/ruby/site_ruby/1.8/rubygems/exceptions.rb:82

I ran it on Ruby 1.8.6-p383, but on Ruby 1.9.1 and Ruby Enterprise Edition 1.8.7 I have same error.

Environment:
rufus-tokyo 1.0.1
ffi 0.5.1
tokyocabinet 1.4.36
Slackware 13.0 x86

**Comment by ghost** [comment]
Sorry, first line should be formatted thus:

require 'rubygems'
require 'rufus/tokyo'
t = Rufus::Tokyo::Table.new('table.tct')

I forgot about '>' character is a quotation ;)

**Comment by jmettraux** [comment]
closing for now, seems it's a Slackware issue :(
