### ISSUE TITLE
B+ Database Segmentation Fault

### ISSUE THREAD

**Issue by dustalov** [jmettraux/rufus-tokyo#29]
Got a segmentation fault on TokyoCabinet B+ when doing Tokyo::Cabinet#getdup at non-existant key.

Way to reproduce:
    db = Rufus::Tokyo::Cabinet.new('data.tcb')
    db.putdup('a', 'v')
    p db.getdup('a') # fine
    p db.getdup('b') # segfault
    db.close
Thanks!

**Comment by jmettraux** [comment]
Thanks for the report, I will fix that ASAP

**Comment by jmettraux** [comment]
segfault when getdup(unknown_key). Fixed, thanks Dmitry. Closed by 632976b8681723a5225e11469359577c17d74c3b

**Comment by jmettraux** [comment]
just release 1.0.6 which contains the fix. Many thanks !
