### ISSUE TITLE
Attempts to install ffi on jruby

### ISSUE THREAD

**Issue by roja** [jmettraux/rufus-tokyo#30]
The current GEM attempts to install ffi on jruby thus causing the install to fail.

**Comment by roja** [comment]
braeburn:words roja$ sudo gem install rufus-tokyo
Building native extensions.  This could take a while...
ERROR:  Error installing rufus-tokyo:
    ERROR: Failed to build gem native extension.

/Users/roja/.rvm/rubies/jruby-1.4.0/bin/jruby extconf.rb
WARNING: JRuby does not support native extensions or the `mkmf' library.
         Check wiki.jruby.org for alternatives.
extconf.rb:4: undefined method`dir_config' for main:Object (NoMethodError)

Gem files will remain installed in /Users/roja/.rvm/gems/jruby-1.4.0/gems/ffi-0.6.0 for inspection.
Results logged to /Users/roja/.rvm/gems/jruby-1.4.0/gems/ffi-0.6.0/ext/ffi_c/gem_make.out
braeburn:words roja$ sudo gem install ffi
Building native extensions.  This could take a while...
ERROR:  Error installing ffi:
    ERROR: Failed to build gem native extension.

**Comment by jmettraux** [comment]
So I guess, I will remove the dependency on ffi and then let the regular ruby users complaints go to you.

**Comment by jmettraux** [comment]
removed hard dependency on ffi so that JRuby installs stop failing. Closed by bdd2eadd296b78acde189804358847fe2c61c9c5.

**Comment by jmettraux** [comment]
rufus-tokyo 1.0.7 out.

**Comment by roja** [comment]
lol... Well, doubtless there is a nice way to make the gem detect it's installation platform? Much appreciate the the quick work though!

**Comment by jmettraux** [comment]
you're welcome, though dependencies are managed via rubygems, which has [currently] no conditional declaration mecha. I had added the dep because people complained. Preventing non-installation has priority, so here we go, removed.

Cheers,
